[build-system]
requires = ["setuptools>=45", "wheel", "setuptools_scm[toml]>=6.2"]
build-backend = "setuptools.build_meta"

[project]
name = "aiofranka"
version = "0.3.0"
description = "A Python package for Franka robot control using asyncio."
readme = "README.md"
requires-python = ">=3.8"
license = {text = "MIT"}
authors = [
    {name = "MIT Improbable AI Lab"}
]
classifiers = [
    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: 3.8",
    "Programming Language :: Python :: 3.9",
    "Programming Language :: Python :: 3.10",
    "Programming Language :: Python :: 3.11",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
]
dependencies = [
    "pylibfranka",
    "ruckig",
    "numpy",
    "scipy",
    "mujoco",
    "tqdm",
    "requests",
    "pyzmq",
    "msgpack",
]

[project.scripts]
aiofranka = "aiofranka.__main__:main"

[project.optional-dependencies]
docs = [
    "sphinx>=7.0.0",
    "sphinx-rtd-theme>=2.0.0",
]
teleop = [
    "pyspacemouse",
    "aprilcube",
    "pyrealsense2",
]
robotiq = [
    "minimalmodbus",
    "pyrobotiqgripper",
]

[project.urls]
Homepage = "https://github.com/Improbable-AI/aiofranka"
Repository = "https://github.com/Improbable-AI/aiofranka"
